@base_url = http://localhost:3000
@auth_token = {{authenticate.response.body.accessToken}}

# @name create_account

POST {{base_url}}/accounts
Content-Type: application/json

{
    "name": "Andre Rest",
    "email": "andre@test.com",
    "password": "123456"
}

###

# @name authenticate

POST {{base_url}}/sessions
Content-Type: application/json

{
    "name": "Andre Rest",
    "email": "andre@test.com",
    "password": "123456"
}

###

# @name create_question

POST {{base_url}}/questions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "title": "Nova pergunta-2",
    "content": "Conteudo da nova pergunta"
}

###

# @name fetch_recent_questions

GET {{base_url}}/questions?page=2
Content-Type: application/json
Authorization: Bearer {{auth_token}}